export { default as EquipmentAboutScreen } from './ui/EquipmentAboutScreen.vue'
export { default as EquipmentFeaturesScreen } from './ui/EquipmentFeaturesScreen.vue'
export { default as EquipmentFeedbackScreen } from './ui/EquipmentFeedbackScreen.vue'
export { default as EquipmentProductsScreen } from './ui/EquipmentProductsScreen.vue'
export { default as EquipmentTableScreen } from './ui/EquipmentTableScreen.vue'
export { default as EquipmentTopBannerScreen } from './ui/EquipmentTopBannerScreen.vue'
