export { default as SystemAreasInfoScreen } from './ui/SystemAreasInfoScreen.vue'
export { default as SystemDiagramScreen } from './ui/SystemDiagramScreen.vue'
export { default as SystemDownloadScreen } from './ui/SystemDownloadScreen.vue'
export { default as SystemFeaturesScreen } from './ui/SystemFeaturesScreen.vue'
export { default as SystemFeedbackScreen } from './ui/SystemFeedbackScreen.vue'
